services:
  redis:
    image: cgr.dev/chainguard/redis
    ports:
      - '6379:6379'
  giropops-senhas:
    build:
      context: .
      # target: builder
    # flask requires SIGINT to stop gracefully
    # (default stop signal from Compose is SIGTERM)
    stop_signal: SIGINT
    ports:
      - '5000:5000'
    environment:
      - REDIS_HOST=redis
    volumes:
      - .:/code
    depends_on:
      - redis